In [47]:
import numpy as np

print(np.__version__)
oneDArr = np.array([1,2,3,4])
twoDArr = np.array([[1,2,3,4],[5,6,7,8]])
threeDArr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[1, 2, 3, 4], [5, 6, 7, 8]]])
print(oneDArr)
print("*********************")
print(twoDArr)
print("*********************")
print(threeDArr)
print("*********************")
print(type(oneDArr))
print("*********************")
print(oneDArr.ndim)
print(twoDArr.ndim)
print(threeDArr.ndim)

2.1.3
[1 2 3 4]
*********************
[[1 2 3 4]
 [5 6 7 8]]
*********************
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
*********************
<class 'numpy.ndarray'>
*********************
1
2
3


In [48]:
one = np.ones(4, dtype = int)
onesMatrix = np.ones((2,2), dtype = int)
print(one)
print("*********************")
print(onesMatrix)

[1 1 1 1]
*********************
[[1 1]
 [1 1]]


In [49]:
reArrangedOneDArr = oneDArr.reshape(2,2)
reArrangedThreeDArr = threeDArr.reshape(4,4)
print(reArrangedOneDArr)
print("*********************")
print(reArrangedThreeDArr)

[[1 2]
 [3 4]]
*********************
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [50]:
raveledArr = twoDArr.ravel()
flattenedArr = threeDArr.flatten()
print(raveledArr)
print("*********************")
print(flattenedArr)

[1 2 3 4 5 6 7 8]
*********************
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


In [51]:
transposeOfTwoDArr = twoDArr.transpose()
print(transposeOfTwoDArr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [62]:
ls=np.linspace(1,10,50)
print(ls)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [58]:
arrOne = np.array([1, 2, 3, 4, 5, 6])
arrTwo = np.array([7, 8, 9, 10, 11, 12])
arrOneTwoD = np.array([[1, 2, 3], [4, 5, 6]])
arrTwoTwoD = np.array([[7, 8, 9], [10, 11, 12]])
addResult = np.add(arrOne, arrTwo)
subtractResult = np.subtract(arrOne, arrTwo)
divideResult = np.divide(arrOne, arrTwo)
multiplyResult = np.multiply(arrOne, arrTwo)
dotProductResult = np.dot(arrOne, arrTwo)
crossProductResult = np.cross(arrOneTwoD, arrTwoTwoD)
print(addResult)
print("*********************")
print(subtractResult)
print("*********************")
print(divideResult)
print("*********************")
print(multiplyResult)
print("*********************")
print(dotProductResult)
print("*********************")
print(crossProductResult)

[ 8 10 12 14 16 18]
*********************
[-6 -6 -6 -6 -6 -6]
*********************
[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]
*********************
[ 7 16 27 40 55 72]
*********************
217
*********************
[[-6 12 -6]
 [-6 12 -6]]


In [59]:
np.char.splitlines("Dev\nValley\nSoftware\nHouse")

array(list(['Dev', 'Valley', 'Software', 'House']), dtype=object)